### ISSUE TITLE
error in Step 8/21

### ISSUE THREAD

**Issue by johnfelipe** [ilgabrie/IDE_Streamsets_Spark_Jupyter#2]
```
Step 8/21 : RUN $CONDA_DIR/envs/${conda_env}/bin/python -m ipykernel install --user --name=${conda_env} &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER
 ---> Running in 38b392c95344
Traceback (most recent call last):
  File "/opt/conda/envs/python36/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/envs/python36/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/conda/envs/python36/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/ipykernel/connect.py", line 16, in <module>
    import jupyter_client
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write'
The command '/bin/bash -o pipefail -c $CONDA_DIR/envs/${conda_env}/bin/python -m ipykernel install --user --name=${conda_env} &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER' returned a non-zero code: 1
ERROR: Service 'jupyter-notebook' failed to build : Build failed

```

**Comment by johnfelipe** [comment]
```
nano /root/IDE_Streamsets_Spark_Jupyter/Dockerfile-jupyter

##
ARG conda_env=python36
ARG py_ver=3.6
**RUN pip install --upgrade jupyter_client**

##

```

solved
